const ORDER_STATUS_FLOW = ["NEW", "ACCEPTED", "PREPARING", "READY", "DELIVERED", "CLOSED"];
const PAYMENT_STATUSES = ["UNPAID", "AUTHORIZED", "PAID", "PARTIALLY_REFUNDED", "REFUNDED", "VOIDED"];
const ORDER_TYPES = [
  "DINE_IN",
  "TAKEOUT",
  "DELIVERY",
  "ROOM_SERVICE",
  "POOL_SERVICE",
  "BANQUET",
  "BAR",
  "CAFE",
  "FOOD_COURT",
  "CATERING",
  "QR_ORDER",
  "MOBILE_ORDER"
];

module.exports = {
  ORDER_STATUS_FLOW,
  PAYMENT_STATUSES,
  ORDER_TYPES
};
